DriverAvailability: driverAvailability index page
ucsb-cs156-w24/proj-gauchoride-w24-7pm-3 pull request #38
Opened 2024-03-06 01:14 UTC by wzqd

In this pr, I added index page for Driver Availability and completed tests.

![DriverAvailabilityIndex](https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-3/assets/48678145/f4e7dbd9-def9-45cc-b57c-1027d618cf09)

close #17

2024-03-08 00:37 UTC, cydthe submitted a review, later dismissed
LGTM

2024-03-08 01:56 UTC, Rytuose approved these changes
LGTM

2024-03-08 02:11 UTC, Rytuose submitted a review, later dismissed
LGTM

2024-03-08 02:33 UTC, calee14 submitted a review, later dismissed
LGTM

2024-03-10 00:56 UTC, andrewpengucsb requested changes

2024-03-10 00:56 UTC, andrewpengucsb commented on frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
> +    // });
Remove commented test

2024-03-10 00:56 UTC, andrewpengucsb commented on frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
> +    // });
Other than that good to go, ping me when you fix

2024-03-10 07:33 UTC, wzqd commented on frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
> +    // });
I have removed the commented tests. thx for the review

2024-03-11 23:39 UTC, andrewpengucsb approved these changes

2024-03-12 06:52 UTC, Rytuose approved these changes
LGTM

2024-03-12 16:04 UTC, merged