Driver Availability: Added Navbar
ucsb-cs156-w24/proj-gauchoride-w24-7pm-3 pull request #54
Opened 2024-03-07 06:24 UTC by Rytuose

Closes #52

2024-03-08 00:39 UTC, calee14 approved these changes
LGTM

2024-03-08 01:58 UTC, cydthe approved these changes
LGTM

2024-03-11 23:55 UTC, andrewpengucsb requested changes

2024-03-11 23:55 UTC, andrewpengucsb commented on frontend/src/App.js
> +          (hasRole(currentUser, "ROLE_ADMIN") || hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_RIDER")) && <Route exact path="/driverAvailability/" element={<DriverAvailabilityInd
Regular riders should not be able to see when drivers are available

2024-03-11 23:55 UTC, andrewpengucsb commented on frontend/src/main/components/Nav/AppNavbar.js
> +                  <NavDropdown.Item as={Link} to="/driverAvailability">Dashboard</NavDropdown.Item>
Dashboard is incorrect, probably forgot to change when copying?

2024-03-14 02:11 UTC, shamitagurusu commented
LGTM 👍

2024-03-14 02:26 UTC, andrewpengucsb approved these changes
LGTM

2024-03-14 02:34 UTC, shamitagurusu commented
LGTM 👍 👍

2024-03-14 02:36 UTC, shamitagurusu approved these changes

2024-03-14 02:37 UTC, merged